---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.6
    run_list:
      - recipe[apt]
  - name: debian-7.7
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[recpt1::default]
    attributes:
